### ISSUE TITLE
Wired and remote isn't turning on, what am I doing wrong?

### ISSUE THREAD

**Issue by mikekay1** [Kaldek/rat-ratgdo#10]
This is what I followed -- 
![image](https://github.com/Kaldek/rat-ratgdo/assets/52670539/dab5dce0-4e8b-48d7-a2ba-ce3f817a101e)

the black wire leads to R on the remote (confirmed)

in the next post is my wiring at GDO

**Comment by mikekay1** [comment]
![20231027_213744](https://github.com/Kaldek/rat-ratgdo/assets/52670539/c227e6cd-3fad-4dcb-b6c1-c19576f5db84)

**Comment by Kaldek** [comment]
Hi mate, it's possible you followed one of my busted-ass schematics which Fritzing keeps borking.  Check the v7 schematic and make sure your design follows that.  Most importantly make sure you don't have the red wire shorted to ground like I did in the v6 diagram.   

If this was the problem I am really sorry.

**Comment by mikekay1** [comment]
Hey Kal, thanks for the quick reply -- Ah shit I did follow v6 I thought that was the newest one. but still shouldn't remote work even with the esp32 off?

**Comment by mikekay1** [comment]
for additional reference, I followed this from the supported boards readme:

https://github.com/Kaldek/rat-ratgdo/blob/main/ratgdo%20open%20source%20ESP-32_schem_v1.png

**Comment by Kaldek** [comment]
> Hey Kal, thanks for the quick reply -- Ah shit I did follow v6 I thought that was the newest one. but still shouldn't remote work even with the esp32 off?

If the red wire is grounded the wall remote won't get any power, regardless of the ESP32.  Don't feel too bad about this BTW, when I was first reverse engineering this earlier in the week I grounded out the red wire like ten frickin' times.

**Comment by Kaldek** [comment]
> for additional reference, I followed this from the supported boards readme:
> 
> https://github.com/Kaldek/rat-ratgdo/blob/main/ratgdo%20open%20source%20ESP-32_schem_v1.png

I'm re-checking that diagram now and it looks correct. The other thing to be aware of is whether you may have the MOSFET pins flipped around.  Ignore the pin *numbering* on that diagram, it's Fritzing having the icons totally wrong.  

Let me upload one with Source, Gate, and Drain labelled.

**Comment by mikekay1** [comment]
but regardless, the remote should turn on even if the esp32 isn't on right? like doesn't this whole system work without anything turned on because it runs in parallel?

I had a buddy whos an electrical engineer check my work. Im pretty sure I am good with the mosfets, I got them back to back. Let me take a pic.

**Comment by Kaldek** [comment]
Updated image:
https://github.com/Kaldek/rat-ratgdo/blob/main/images/ratgdo%20open%20source%20ESP-32_schem_v2.png

> but regardless, the remote should turn on even if the esp32 isn't on right? like doesn't this whole system work without anything turned on because it runs in parallel?

Not quite.  If the passive circuit design is wrong the whole Red wire is permanently grounded.

**Comment by mikekay1** [comment]
Its impossible to take a picture of breadboard its so jam packed because I wanted to make aure I could fit it on a d1

**Comment by Kaldek** [comment]
> Its impossible to take a picture of breadboard its so jam packed because I wanted to make aure I could fit it on a d1

Have a look at my D1 Mini breadboard that was my first working prototype and let me know if yours follows this?
https://github.com/Kaldek/rat-ratgdo/blob/main/Breadboard_working.png

**Comment by mikekay1** [comment]
Yea followed it to a T, i assumed this green wire leads to the center pin...

![Screenshot_20231027_222435_Chrome](https://github.com/Kaldek/rat-ratgdo/assets/52670539/427ecf6a-b272-4b13-9546-9453dc395925)

**Comment by Kaldek** [comment]
> Yea followed it to a T, i assumed this green wire leads to the center pin...

Yep, sure does.  The pins of the MOSFET are Source/Gate/Drain so the middle pin is Gate.

Check your MOSFET to make sure it's not shorted Gate to Ground.  It is the *classic* MOSFET failure mode.

**Comment by mikekay1** [comment]
Hey bro, totally ripper, I looked at your schematic and actually lined up the ends pins on the n7000's back to back. what I outta do is short it to the center pin, because soo as I unplugged the chip it stopped pulling to ground and remote turned on. I think I need another drink haha!

**Comment by Kaldek** [comment]
Also make sure with your ESP-32 setup that you check our updated notes.  We're pivoting back to using the v2.0 web installer option for anyone with an ESP-32 because the ESPHome flasher web page doesn't have the v2.5 ESP-32 settings available, and Paul Wieland hasn't even started offering the v2.5 settings on his downloader.

On an ESP-32, TX should therefore be connected to GPIO16!

**Comment by mikekay1** [comment]
Yea I used 2.0, read that in the other thread, no need for 2.5 because I dont need dry contact support or additional(?) trip sensors... I will put a ultrasonic sensor attached to this esp32 for car detection as well...

**Comment by mikekay1** [comment]
> Also make sure with your ESP-32 setup that you check our updated notes. We're pivoting back to using the v2.0 web installer option for anyone with an ESP-32 because the ESPHome flasher web page doesn't have the v2.5 ESP-32 settings available, and Paul Wieland hasn't even started offering the v2.5 settings on his downloader.
> 
> On an ESP-32, TX should therefore be connected to GPIO16!
> 
> I mean, you _could_ try to use ESPHome and setup a v2.5 wiring layout but it's currently, ah, "[fun](https://github.com/Kaldek/rat-ratgdo/issues/3)"?

So yea, I actually followed that thread for pinouts but followed the schematics from v 2.0 is that not what I am supposed to be doing?

as for GPIO16, I went with 23,22 and 21 is that also not correct?

**Comment by Kaldek** [comment]
> as for GPIO16, I went with 23,22 and 21 is that also not correct?

Yeah I'm sorry this is a bit confusing but it's IO16/GPIO16 rather than GPIO21.  I hadn't gotten around to updating the schematic.

**Comment by mikekay1** [comment]
kk noted, I will update! and try again 👍

**Comment by Kaldek** [comment]
> kk noted, I will update! and try again 👍

Give me 5 minutes to make sure I get it right.  I've got a rotten hangover.

**Comment by Kaldek** [comment]
Righto I think I've fixed this up.
https://github.com/Kaldek/rat-ratgdo/blob/main/images/ratgdo%20open%20source%20ESP-32_schem_v3.png

**Comment by mikekay1** [comment]
let me give it a whirl

**Comment by mikekay1** [comment]
one quick question, if using 2n7000 x 2 configuration, are the gates in the same orientation as the schematic provided? I'm  waiting on the additional transistor from amazon.

**Comment by Kaldek** [comment]
> one quick question, if using 2n7000 x 2 configuration, are the gates in the same orientation as the schematic provided? I'm waiting on the additional transistor from amazon.

They should be correct as per the schematic.  On the RX line, Gate is connected to the Red wire whereas on TX the Drain is connected to it.

**Comment by mikekay1** [comment]
Yea sorry im a bit of a noob qhen it comes to bill of materials, i dont experience with these transitors.

Soon as i plih in my circuit the damn wall unit turns off aomething is wrong on my board and I cant pinpoint it

**Comment by Kaldek** [comment]
> Yea sorry im a bit of a noob when it comes to bill of materials, i dont experience with these transitors.
> 
> Soon as i plih in my circuit the damn wall unit turns off aomething is wrong on my board and I cant pinpoint it

Did you validate that neither of your MOSFETs have shorted Gate to Source?  Remove them from the board and do a continuity test.  That's step #1.  After that it's just that slow process of tracing each wire.  It's particularly tricky on breadboards.

Common issues I've had with my breadboard setups over the years:

- Accidentally connecting to the ground plane
- Not seeing that I've got two separate circuits connected to each other
- Getting parts installed backwards

**Comment by sanjay900** [comment]
> > Yea sorry im a bit of a noob when it comes to bill of materials, i dont experience with these transitors.
> > Soon as i plih in my circuit the damn wall unit turns off aomething is wrong on my board and I cant pinpoint it
> 
> Did you validate that neither of your MOSFETs have shorted Gate to Source? Remove them from the board and do a continuity test. That's step 1. After that it's just that slow process of tracing each wire. It's particularly tricky on breadboards.
> 
> Common issues I've had with my breadboard setups over the years:
> 
>     * Accidentally connecting to the ground plane
> 
>     * Not seeing that I've got two separate circuits connected to each other
> 
>     * Getting parts installed backwards

The amount of times i had MOSFETs with shorted Gate to Sources yesterday....

**Comment by mikekay1** [comment]
Good tips here, ill try pulling the mosfets and tracing back.

Can someone give me an true to esp32 wiring diagram? Is that the auper updated one provided by @Kaldek?

**Comment by poldim** [comment]
Can you guys confirm that schematics/ratgdo open source_schem_v7.png is accurate?  I can share the easyeda layout:

<img width="886" alt="image" src="https://github.com/Kaldek/rat-ratgdo/assets/16869713/0d306485-70d8-4f19-94a1-356b7ee3ae17">

**Comment by rlowens** [comment]
> Can you guys confirm that schematics/ratgdo open source_schem_v7.png is accurate? 

Accurate to what? It does match your layout here. In ratgdo v2.0 the 10k resistor on the gate of IRLB8721 is in-series to D1 where we think it makes more sense to have it as a pull-down between gate and ground, as you have matched here.

> I think the matches the schematic just a bit cleaner.

Very nice, but I'd also like the Source/Gate/Drain labeled on the MOSFETs for those of us that aren't great at reading them.
Mine:
![image](https://github.com/Kaldek/rat-ratgdo/assets/35885181/b676a10e-e8f4-4fd9-8dca-08ae768354fa)

> Personally, I'd like to use D5/D6/D7 for the connections as they allow you to keep D1/D2 for hardware I2C.
That sounds fine to me. Just modify your device .yaml to use that.

**Comment by rlowens** [comment]
> Good tips here, ill try pulling the mosfets and tracing back.
> 
> Can someone give me an true to esp32 wiring diagram? Is that the auper updated one provided by @Kaldek?

https://github.com/Kaldek/rat-ratgdo/blob/main/schematics/ratgdo%20open%20source%20ESP-32_schem_v3.png  looks great

**Comment by Kaldek** [comment]
> Can you guys confirm that schematics/ratgdo open source_schem_v7.png is accurate? I can share the easyeda layout
> I think the matches the schematic just a bit cleaner.

I like it mate, it's very clean and easy to read; easier than Ki-Cad even.  Can you do a pull request for creation of an easyeda folder with the files in it please.

**Comment by mikekay1** [comment]
> > Can you guys confirm that schematics/ratgdo open source_schem_v7.png is accurate? I can share the easyeda layout
> > I think the matches the schematic just a bit cleaner.
> 
> I like it mate, it's very clean and easy to read; easier than Ki-Cad even. Can you do a pull request for creation of an easyeda folder with the files in it please.

I also used this schematic but damn thing still aint working... Ill get back to it. If you are wanting for close this issue. It has more than enough revelent info in it.

Thanks for everyone's call to arms!

**Comment by poldim** [comment]
> > Can you guys confirm that schematics/ratgdo open source_schem_v7.png is accurate? I can share the easyeda layout
> > I think the matches the schematic just a bit cleaner.
> 
> I like it mate, it's very clean and easy to read; easier than Ki-Cad even. Can you do a pull request for creation of an easyeda folder with the files in it please.

I got a bit carried away  😛 

<img width="743" alt="image" src="https://github.com/Kaldek/rat-ratgdo/assets/16869713/be8b7e27-b1bd-4b76-a340-67204840172c">

I'll happily share but I want to build one of these things before I upload it.

**Comment by Kaldek** [comment]
> > > Can you guys confirm that schematics/ratgdo open source_schem_v7.png is accurate? I can share the easyeda layout
> > > I think the matches the schematic just a bit cleaner.
> > 
> > 
> > I like it mate, it's very clean and easy to read; easier than Ki-Cad even. Can you do a pull request for creation of an easyeda folder with the files in it please.
> 
> I got a bit carried away 😛
> 
> <img alt="image" width="743" src="https://user-images.githubusercontent.com/16869713/279248252-be8b7e27-b1bd-4b76-a340-67204840172c.png">
> I'll happily share but I want to build one of these things before I upload it.

You know, I just **knew** someone who really liked laying out boards would come along.  This is quite the PCB.

**Comment by Kaldek** [comment]
> > > Can you guys confirm that schematics/ratgdo open source_schem_v7.png is accurate? I can share the easyeda layout
> > > I think the matches the schematic just a bit cleaner.
> > 
> > 
> > I like it mate, it's very clean and easy to read; easier than Ki-Cad even. Can you do a pull request for creation of an easyeda folder with the files in it please.
> 
> I also used this schematic but damn thing still aint working... Ill get back to it. If you are wanting for close this issue. It has more than enough revelent info in it.
> 
> Thanks for everyone's call to arms!

@mikekay1 do you want to try with 2n7000 if not already, or an RFP30N06LE?  Another guy just tried ten different IRLB8721 and none of them worked, which is...very weird.
https://github.com/Kaldek/rat-ratgdo/issues/5#issuecomment-1786406085

I am also very curious what your ESPHome console log is saying.  Is it seeing status updates (RX working) but can't send commands (TX not working), or getting lots of errors like "Collision detected"?

**Comment by sanjay900** [comment]
> > > > Can you guys confirm that schematics/ratgdo open source_schem_v7.png is accurate? I can share the easyeda layout
> > > > I think the matches the schematic just a bit cleaner.
> > > 
> > > 
> > > I like it mate, it's very clean and easy to read; easier than Ki-Cad even. Can you do a pull request for creation of an easyeda folder with the files in it please.
> > 
> > 
> > I also used this schematic but damn thing still aint working... Ill get back to it. If you are wanting for close this issue. It has more than enough revelent info in it.
> > Thanks for everyone's call to arms!
> 
> @mikekay1 do you want to try with 2n7000 if not already, or an RFP30N06LE? Another guy just tried ten different IRLB8721 and none of them worked, which is...very weird. [#5 (comment)](https://github.com/Kaldek/rat-ratgdo/issues/5#issuecomment-1786406085)
> 
> I am also very curious what your ESPHome console log is saying. Is it seeing status updates (RX working) but can't send commands (TX not working), or getting lots of errors like "Collision detected"?

I myself used two 2n7000s because they didn't have IRLB8721s in stock at my local electronics shop

**Comment by mikekay1** [comment]
Im still trying to solve this, sorry guys thought I had it figured out! Thanks for all the comments, Ive double checked the circuit a million times and rebuilt countless times. My remote on the wall just shuts off. I have a model with batter backup do I need to bypass that for this to work? Are my grounds getting messed up? I wish I could send a picture of the board juat really hard to see anywl yall available on discord. This is driving me nuts!

I know I have the red wire correct, obstruction sensors connected. Even swapped to dual 2n7000 just to see if I could make it the same as Kaldeks protype board, might try and make it exactly! The same just for shits and giggles...
