### ISSUE TITLE
Wall switch doesn’t work

### ISSUE THREAD

**Issue by thadude3** [Kaldek/rat-ratgdo#101]
If I have the ratgdo installed my wall switch doesn’t work. The light is on and it sometimes flickers but does t work. It’s a 2.0 wall switch. The ratgdo works fine. All the sensors statuses etc. there’s no errors in the logs. It’s just the wall switch that stops working. Is it a wiring issue? Anyone have suggestions?

**Comment by Kaldek** [comment]
Sorry for the delayed response.  Yes this is likely a wiring issue where the 12v line for the wall controller is being pulled down and it's not getting power.
