### ISSUE TITLE
8010 w/ (2) 2N7000 not working

### ISSUE THREAD

**Issue by dubstomp** [Kaldek/rat-ratgdo#107]
Reading status of door, obstruction sensors and light correctly. Won't operate door or light, toggle included. Tried reflashing but no change. Bad solder job but everything going where it should be from what I can tell. (Copied from: https://imgur.com/a/Cc6UmzT and https://github.com/Kaldek/rat-ratgdo/blob/main/schematics/ratgdo%20open%20source%20D1%20Mini_schem_v6.png)

![IMG_0890](https://github.com/user-attachments/assets/6aa0d0d5-e869-49b2-88b3-5887398af0a6)
![IMG_0888](https://github.com/user-attachments/assets/22f3125b-b06a-470c-a18d-1b631eab2edb)
![IMG_0887](https://github.com/user-attachments/assets/5818b95a-b491-4afb-81a2-6d858e36baad)

**Comment by Kaldek** [comment]
Hi mate, sorry for the lack of replies.  I can only recommend different MOSFETs, as the gate voltage threshold for different manufacturers of the 2n7000 varies too much.  I got lucky with mine.  

I really do need to update the guidance on what MOSFET to use.  I thought I'd already done that but looking at the main page it still references the 2n7000.
