### ISSUE TITLE
880LWM Issue

### ISSUE THREAD

**Issue by njschwartz** [Kaldek/rat-ratgdo#108]
Wonder if anyone else has experienced something similar.  I have the 88LWM connected to my Jackshaft 8500W opener.  I built a prototype ratratgdo using the three resistor/2N7000.  At first I didn't think it was working at all as when I wired it up it wouldn't connect and I could hear a buzzing from the 88LWM switch when I would try to trigger something in ESPHome.  I finally tried disconnecting the switch and only connecting the ratratgdo and it works perfectly. But as soon as I reconnect the wall switch it stops again like the two are interfering with each other.  Is there something I am missing as far as wiring a switch in (I know on the ratgdo from Paul he has a passthrough of some sort on the board.  I am not really clear how I would wire that. Or is this an issue with my build or the 2N7000's maybe?  I would love to hear if anyone else has has this issue and what I might do to troubleshoot it.  I appreciate it!

**Comment by Kaldek** [comment]
Generally these are indeed wiring issues and the 12v red wire is being pulled down causing it to not get power.  Identifying exactly what caused this usually means busting out the oscilloscope to confirm the behaviour on that wire and then working backwards from there.
