### ISSUE TITLE
KiCad files missing connection for BLK/OBST

### ISSUE THREAD

**Issue by dpeart** [Kaldek/rat-ratgdo#18]
I don't see the connect to the OBST pins in the PCG view that are in the schematic.

Am I missing something?
thanks

**Comment by Kaldek** [comment]
Hi @dpeart let me bring in @bjhiltbrand as I haven't dived into them in detail yet.

**Comment by bjhiltbrand** [comment]
Now that I look at it, I think I swapped the White and Black wires on my schematic. I will fix that. Sorry about that.

**Comment by bjhiltbrand** [comment]
@Kaldek I think this one can be closed, too.

**Comment by rlowens** [comment]
Merged.
