### ISSUE TITLE
Seeed Studio XIAO ESP32-S3 

### ISSUE THREAD

**Issue by dolfelt** [Kaldek/rat-ratgdo#34]
I am looking at using a Seeed Studio XIAO ESP32-S3 for this ratgdo. Would that be a suitable board, or would it be best to stick with the ESP32 D1 Mini?

**Comment by CrazyCoder** [comment]
It should work fine with the `esphome-ratgdo` with some config changes (GPIO pins, board, etc).
If your GDO is supported by `esphome-ratgdo` firmware, you are good to go.

**Comment by dolfelt** [comment]
Ok, thanks! Assumed some pin config and physical changes.
