### ISSUE TITLE
A companion device for door close alerts from automations

### ISSUE THREAD

**Issue by CrazyCoder** [Kaldek/rat-ratgdo#40]
Just to document my little project. It's ESPHOME esp2866 simple device with a buzzer and 4x4 WS2812 LED matrix I use to alert when any automation is about to close the door.

ESPHOME config: [gdalert.yaml](https://gist.github.com/CrazyCoder/cafb68fbc308315d7ad1a71da998df72).

![chrome_2023-11-13_08-11-41](https://github.com/Kaldek/rat-ratgdo/assets/122834/8d3278d2-2e27-48a2-bb5e-34dba77baf26)

<img width="482" alt="chrome_2023-11-13_08-09-32" src="https://github.com/Kaldek/rat-ratgdo/assets/122834/7554e5ba-c316-49ed-852c-166d856c44bb">

<img width="396" alt="chrome_2023-11-13_08-09-51" src="https://github.com/Kaldek/rat-ratgdo/assets/122834/24b0aeaf-c82e-44e4-8c0f-a2ad0bf05f9a">

![chrome_2023-11-13_08-10-20](https://github.com/Kaldek/rat-ratgdo/assets/122834/7a0665f6-5a06-4174-adfb-5cc2ff556e54)

![chrome_2023-11-13_08-10-57](https://github.com/Kaldek/rat-ratgdo/assets/122834/635dfcc9-1517-4400-b4c8-29f9126d5f54)

Bottom shield is completely optional, and I use it only for mounting with a Velcro-like adhesive tape. You can opt for a custom 3D-printed enclosure or your own creative way of attaching it to a surface.

BOM:

- [ESP8266 D1 Mini](https://www.amazon.com/Organizer-ESP8266-Internet-Development-Compatible/dp/B081PX9YFV/)
- [x2 proto shields for D1](https://www.amazon.com/gp/product/B07L756KQS/)
- [Active buzzer module](https://www.amazon.com/gp/product/B07GDMV5DB/) (use 3.3V for VCC and D5 for control, inverted)
- [4x4 WS2812 matrix](https://www.amazon.com/CANADUINO-Matrix-Fully-Addressable-WS2812B/dp/B07LDYDDSZ/) (controlled via RX pin)

You can use any 5V addressable LED strip/matrix/etc, but this one was easy to mount and looks nice.

Trigger a switch from Home Assistant automation. 5s and 10s switches turn off automatically after the specified time. You can control the light and buzzer independently.

<img width="259" alt="chrome_2023-11-13_08-20-02" src="https://github.com/Kaldek/rat-ratgdo/assets/122834/569e7191-02dc-462c-9eea-32bdfeaa57ad">

**Comment by Kaldek** [comment]
If you would like this content added to the repo as an optional addition, let me know.
