### ISSUE TITLE
Wall switch goes dark

### ISSUE THREAD

**Issue by dpeart** [Kaldek/rat-ratgdo#53]
Anyone have issues what the wall switch becomes disabled?  After opening/closing the door from HA the switch will work for a bit, then go dark again.

I've seen video what you can disable the wall switches intentionally, but why would it happen automatically?

**Comment by Kaldek** [comment]
If the wall switch goes dark, it means the +12v red wire is being pulled to ground by something.

**Comment by dpeart** [comment]
That is what I suspected.  I've installed 8 of the 10 boards and all but one works.  Well they all work in that they will open/close and report everything, it is just that one also disables the wall switch . . .  usually.

odd
