### ISSUE TITLE
ESP32 WROOM 

### ISSUE THREAD

**Issue by dragosde** [Kaldek/rat-ratgdo#57]
I checked all issues to make sure I am not duplicating. I am not sure where my problem is.
I triple-checked the circuit and tried several GPIO variants with no luck.
Just want to mention that the ESP32 WROOM (The last of the supported boards in the section) can be flashed with the ESPHome port. I did that successfully. 
However, in my case, I have an old GDO, pre 2005 that only has security plus.
The native ratgdo cannot be flashed ("Your board is not supported") and I may miss something as I cannot make the board communicate with the GDO. 
The easiest way would be to get a D1 mini but since I had the ESP32 WROOM laying around I thought I should try it.
If anyone was successful to get this board working with an old GDO I am all ears.
My point here is, maybe mention in the documentation that the ESP WROOM only works for security 2.0 as others have tried and deemed this board supported but not with the older GDOs

**Comment by Kaldek** [comment]
> My point here is, maybe mention in the documentation that the ESP WROOM only works for security 2.0 as others have tried and deemed this board supported but not with the older GDOs

Sorry for the delayed reply here, but I don't see why the ESP WROOM would not work with the older GDOs in **all** circumstances.  That is, I don't see why it would not work when using ESPHome-ratgdo, assuming the ESPHome port of ratgdo has incorporated the support for SecPlus 1.0.  The ESPHome port of ratgdo is fundamentally capable of being tweaked out the wazoo thanks to the use of YAML to define which pins do what.

**Comment by dragosde** [comment]
You may be right. I have too many moving targets: an older GDO 8200 with dumb wall panel that apparently doesn't speak the protocol. Some possible wiring issues as I am getting "collision detected" every now and then.  and the ESP WROOM board. I will try to solve them one at the time. Some D1 minis are on the way. I will flash again and will report back. I am not sure if this issue should be still open

**Comment by Kaldek** [comment]
Closing as requester will report back when resolved.
