### ISSUE TITLE
Bill of materials for schematics folders

### ISSUE THREAD

**Issue by Guy559** [Kaldek/rat-ratgdo#58]
Have been following this repo for past month or so. Amazing work and thank you for the resource.

Would it be possible to add a BOM to each schematics folder? I'd like to ensure I'm ordering the proper SOT pieces for the ESP8266 D1 Wemos boards that I'm having printed for my home openers. I can find plenty of resistors but, frankly, don't know if I should be snagging 1/4W, 1/10W, etc.

A simple BOM to go with each latest schematic would go a long way to supporting those of us who know just enough to be dangerous...

Thanks!

**Comment by Kaldek** [comment]
Very delayed response here, but from the perspective of resistors we're talking very low power so 1/2 a watt or less is fine.
