### ISSUE TITLE
No issue. Just wanted to display my working board. Thank you!

### ISSUE THREAD

**Issue by thauch** [Kaldek/rat-ratgdo#65]
No issue. Just wanted to display my working board. Thank you!
It's been working flawlessly.
I've also been able to update ESPHome in Home Assistant without issue. 

![rat-ratgdo-vero](https://github.com/Kaldek/rat-ratgdo/assets/7277391/813bdeed-1886-4bf8-acec-24f5247d8674)
![rat-ratgdo-enclosure](https://github.com/Kaldek/rat-ratgdo/assets/7277391/b67b2a66-95f0-4207-893b-e1b5185f144c)

**Comment by Kaldek** [comment]
Cheers!  Did you make the YAML change for the board to "d1_mini" to be able to perform the updates?

**Comment by Kaldek** [comment]
Closing due to no extra info.
