### ISSUE TITLE
Error: ESP does not have enough space to store OTA file.

### ISSUE THREAD

**Issue by williamcwallis** [Kaldek/rat-ratgdo#66]
I’m receiving the following error on my setup when trying to update the firmware.

![Screenshot 2023-12-28 at 8 55 53 AM](https://github.com/Kaldek/rat-ratgdo/assets/133121921/4f3f209e-55f1-41a9-a9fa-7588dd38a02e)

Per the instructions on the ESPHome vs Native Ratgdo page, I added the d1_mini board code in my yaml as seen below. 

![Screenshot 2023-12-28 at 9 05 48 AM](https://github.com/Kaldek/rat-ratgdo/assets/133121921/3c9f447c-b5be-437c-9719-a2edb5fa7844)

I am using the following board. https://a.co/d/6W7dEID

Apologies if there is something that I’m missing rather than this being an actual issue. Thanks.

**Comment by CodeFinder2** [comment]
See https://github.com/Kaldek/rat-ratgdo/issues/64

You can use an ESP32.

**Comment by Kaldek** [comment]
Hi mate, did you first reflash it using USB?  The first time you update the settings to "d1_mini" it still doesn't know about that capability, so you must first do a "manual" install via USB.  After that, it knows about the settings and space available.

**Comment by Kaldek** [comment]
For @CodeFinder2 - I deleted your comment only because it missed the context of how I've provided instrructions for ESP8266 boards with 4MB flash.

**Comment by williamcwallis** [comment]
I just flashed it manually via USB. That did that trick. No OTA problems now. Thanks for the help!
