### ISSUE TITLE
Adding support for 2MB and 4MB flash devices in the esphome-ratgdo repo

### ISSUE THREAD

**Issue by Kaldek** [Kaldek/rat-ratgdo#67]
I have created an issue in the esphome-ratgdo repo to ask them for official support for ESP8266 modules with 4MB and 2MB flash, respectively.

ratgdo/esphome-ratgdo#161

**Comment by rlowens** [comment]
As noted there by me, 4MB is already supported.

**Comment by Kaldek** [comment]
Ooof - I realise now that your 2.5i YAML already uses the d1_mini value and supports 4MB modules.

ratgdo/esphome-ratgdo#156

Ugh.  Oh well, just the 2MB section is valid then.

**Comment by Kaldek** [comment]
Well, it seems someone over there doesn't like me as they silently deleted my Issue as if it never existed.  

Good lord.
