### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by CarlKnox** [Kaldek/rat-ratgdo#71]
I'd like to push a branch to be able to create a PR. However,
remote: Permission to Kaldek/rat-ratgdo.git denied to CarlKnox.

**Comment by CarlKnox** [comment]
![IMG_1336](https://github.com/Kaldek/rat-ratgdo/assets/8898791/68c02458-31f3-4881-95d2-c80ba6deabd2)
![IMG_1338](https://github.com/Kaldek/rat-ratgdo/assets/8898791/6ff334f5-330b-4dbd-8e5a-98717b6de7dc)
Just want to PR an alternate proto board layout.

**Comment by CarlKnox** [comment]
Yellow is the 3v3 signals, Though I question using a voltage divider for D7.
I added a header pin for D8 since I'm using homekit-ratgdo. Not using it yet, but it's there when I need it.
```
#define STATUS_OBST_PIN         D8  // output for obstruction status
```

**Comment by Kaldek** [comment]
Hi mate, anyone cane submit a Pull Request.  Did you fork the repository first?

**Comment by CarlKnox** [comment]
Yep,
Tried to push before forking.
Tried PR after branching.
I can try again when I have more time, but thought you might take advantage of the photos in the meantime.

**Comment by Kaldek** [comment]
Yeah, generally it's Fork, Edit, Push.  Noting that I myself are a Github n00b.
